### ISSUE TITLE
md5 hash of the HypoDD archive not correct

### ISSUE THREAD

**Issue by bvicic** [krischer/hypoDDpy#11]
Hi! 

I am getting this error when I try to run hypoddpy. What does it mean?

`md5 hash of the HypoDD archive is not correct`

If i comment out line 84 in hypodd_compiler.py the process continues, but I hit another error...

```
>>> Running ph2dt...
starting ph2dt (v2.1b - 08/2012)...     Tue Feb  4 14:26:49 2020

reading data ...
 > stations =           52
 > events total =         2708
 > events selected =            0
 > phases =            0
forming dtimes...
 > stations selected =            0
 > P-phase pairs total =            0
 > S-phase pairs total =            0

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:
#0  0x7fb0ba39c2da in ???
#1  0x7fb0ba39b503 in ???
#2  0x7fb0b9c30f1f in ???
#3  0x55cdad2c343a in ph2dt
at /scratch/bvicic/Documents/Seismology/hypoDDpy/testrun/hypodd_src/HYPODD/src/ph2dt/ph2dt.f:742
#4  0x55cdad2c49fb in main
at /scratch/bvicic/Documents/Seismology/hypoDDpy/testrun/hypodd_src/HYPODD/src/ph2dt/ph2dt.f:805
Traceback (most recent call last):
  File "pr_run.py", line 34, in <module>
    relocator.start_relocation(output_event_file="relocated_events.xml")
  File "/scratch/bvicic/Documents/Seismology/hypoDDpy/hypoddpy/hypodd_relocator.py", line 133, in start_relocation
    self._run_ph2dt()
  File "/scratch/bvicic/Documents/Seismology/hypoDDpy/hypoddpy/hypodd_relocator.py", line 741, in _run_ph2dt
    raise HypoDDException(msg)
hypoddpy.hypodd_relocator.HypoDDException: Problem running ph2dt
```

Any ideas?
Thanks!

**Comment by krischer** [comment]
Hi,

if the hash is not identical it means that the file is different than the one that was used to originally create this package. It might still work fine though. In your case I'd advise to have a look at all the input files generated by the Python wrappers before they are being fed to the hypoDD binaries and make sure they are correct. That should give some hints as to what is going on.

Cheers!

Lion

**Comment by bvicic** [comment]
Thanks. 

I checked and all seems to be working (after commenting the line as mentioned).

Regarding the 2nd error: the problem was, that my picks did not contain network code. When added, all works as intended!

Thanks!
