### ISSUE TITLE
dependencies in setup.py

### ISSUE THREAD

**Issue by iceseismic** [krischer/hypoDDpy#3]
Hi,
Dependencies in setup.py for obspy.signal ; obspy.mseed fail  ;  ok when replaced just with 'obspy' 
cheers

**Comment by krischer** [comment]
I did not use this code in quite a while but other people did. I just merged PR #2 which should fix the `setup.py` file amongst other things.

Thanks for reporting. Please also report all other problems :-)

Cheers!
